services:
  users:
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    restart: always
    networks:
      - api_net

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - api_net
      
networks:
  api_net:
